import i18n from 'i18n-js';
import * as Localization from 'expo-localization';

function SelectObject(Dict, language){
    var Obj = {};
    for (key in Dict) {
      Obj[key] = Dict[key][language];
    }
    return Obj
  }

const Strings_Dict = {

/*premium report*/
premium_request: {en_us: 'Share your information with a doctor and request a full report.', 
                  zh_hk: '與醫生分享您的信息並要求提供完整報告'},
premium_sure:    {en_us: 'Are you sure?', zh_hk: '您確定嗎？'},
premium_request_button: { en_us: 'Request Full Report', zh_hk: '索取完整報告'}, 
premium_request_title: { en_us: 'Full Report', zh_hk: '完整報告'}, 
premium_report_request: { en_us: 'Full Report Request:', zh_hk: '完整報告要求:'}, 
homescreen_preport: { en_us: 'Request Full Report', zh_hk: '索取完整報告'},
premium_detail: { en_us: 'Click below to share your data with the medical staff at Rainbow Genomics. \
They will prepare a full report for you and also make recommendations about what you can do to reduce your risk.', 
zh_hk: '點擊下面的按鈕, 與Rainbow Genomics的醫務人員共享您的數據。 他們將為您準備一份完整的報告，並就如何降低風險提出建議。'},
preport_status:   { en_us: 'Report Status:', zh_hk: '報告狀態：'},
preport_status_1: { en_us: 'We have received your report request.', zh_hk: '我們已收到您的舉報請求。'},
preport_status_2: { en_us: 'Your report is done and is on the way to you.', zh_hk: '您的報告已完成，正在處理中。'},
preport_request1: { en_us: 'Report Request:', zh_hk: '報告要求：'}, 
preport_request2: { en_us: 'You requested a full report on ', zh_hk: '您要求提供一份完整的報告 '}, 
preport_request3: { en_us: 'The report may take up to three weeks to be signed by a medical director \
and sent to you or your physician.', zh_hk: '該報告可能需要三週的時間才能由醫療主管簽署並發送給您或您的醫師。'}, 

/*tab bar*/
    tab_home:     {en_us: 'Home',     zh_hk: '家'},
    tab_genes:    {en_us: 'Genetics', zh_hk: '遺傳學'},
    tab_settings: {en_us: 'Account',  zh_hk: '帳戶'}, 

    global_low:               { en_us: 'low', 
                                zh_hk: '低' },
    global_moderate:          { en_us: 'moderate', 
                                zh_hk: '適中' },
    global_borderline:        { en_us: 'borderline', 
                                zh_hk: '處於較高風險臨界值' },
    global_elevated:          { en_us: 'elevated', 
                                zh_hk: '較高' },
    global_high:              { en_us: 'high', 
                                zh_hk: '高' },
    global_yes:               { en_us: 'Yes',
                                zh_hk: '是'},
    global_no:                { en_us: 'No',
                                zh_hk: '否'},
    global_show:              { en_us: 'show',
                                zh_hk: '顯示'},
    global_hide:              { en_us: 'hide',
                                zh_hk: '隱藏'},
    global_password:          { en_us: 'Password',
                                zh_hk: '密碼'},
    global_Done:              { en_us: 'Done',
                                zh_hk: '完成'},
    global_ok:                { en_us: 'OK',
                                zh_hk: '好的'},
    global_internet_text_half:{ en_us: 'Please connect to the Internet to ',
                                zh_hk: '請連接網路來'}, 
    global_server_text_half:  { en_us: 'Please contact support to ',
                                zh_hk: '請聯繫客戶支持來'},
    global_dot:               { en_us: '. ',
                                zh_hk: '。'},

    // home screen
    homescreen_title:             { en_us: 'Heart Health', 
                                    zh_hk: '心血管健康' },
    homescreen_view_result:       { en_us: 'View', 
                                    zh_hk: '瞅' },
    homescreen_update_answer:     { en_us: 'Update my answers', 
                                    zh_hk: '更新個人信息' },
    homescreen_risk_event:        { en_us: '10 year risk', 
                                    zh_hk: '十年內患病概率'},
    homescreen_check_status:      { en_us: 'Check Status', 
                                    zh_hk: '查看狀態'},
    homescreen_summary:           { en_us: 'Summary',
                                    zh_hk: '摘要'},
    homescreen_complete_info:     { en_us: 'Complete my information',
                                    zh_hk: '請完善您的信息'}, 
    homescreen_recommend:         { en_us: 'to get personalized recommendations.',
                                    zh_hk: '以獲得私人建議'},
    homescreen_all_question:      { en_us: 'All questions answered',
                                    zh_hk: '信息已完整'},
    homescreen_calculate_risk:    { en_us: 'Calculate Risk',
                                    zh_hk: '計算風險指數'},
    homescreen_question_answered: { en_us: 'Questions Answered',
                                    zh_hk: '已填寫信息'},
    homescreen_calculating_risk:  { en_us: 'Calculating your risk',
                                    zh_hk: '正在計算您的風險指數'},
    home_internet_title:          { en_us: 'No Internet connection',
                                    zh_hk: '無網路連接'},
    home_internet_text:           { en_us: 'Please connect to the Internet to use services.',
                                    zh_hk: '請連接到網路以使用服務'}, 
    home_check_status:            { en_us: 'check status',
                                    zh_hk: '檢查狀態'},
    home_send_file:               { en_us: 'send file to doctor',
                                    zh_hk: '發松文件給醫生'},
    home_server_title:            { en_us: 'Server connection error',
                                    zh_hk: '服務器連接錯誤'},
    home_server_text:             { en_us: 'Unable to reach Blockdoc servers. Please check your networking environment.',
                                    zh_hk: '無法連接到服務器。請檢查您的網路配置。'},
    home_send_file:               { en_us: 'send file to doctor',
                                    zh_hk: '發松文件給醫生'},
    home_server_title:            { en_us: 'Server connection error',
                                    zh_hk: '服務器連接錯誤'},
    home_server_text:             { en_us: 'Unable to reach Blockdoc servers. Please check your networking environment.',
                                    zh_hk: '無法連接到服務器。請檢查您的網路配置。'},

    // home screen - long text
    homescreen_summary_null:      { en_us: 'We cannot estimate your risk yet.',
                                    zh_hk: '我們還不能評估您的風險'}, 
    homescreen_summary_ask:       { en_us: 'Please answer the questions about you and your health. With that information and also the genomics results, we will be able to determine your overall risk.',
                                    zh_hk: '請回答有關您和您的健康的問題。這些信息以及基因檢測的結果將會幫助我們评估您的整體風險。'},  
    homescreen_summary_risk_ask:  { en_us: 'Please answer the questions about you and your health. With that information, we can begin to estimate your risk of a cardiovascular event over the next 10 years.',
                                    zh_hk: '請回答有關您和您的健康的問題。這些信息將會幫助我們評估您未來10年患心血管疾病的基本風險。'}, 

    homescreen_overall_risk_title: { en_us: 'Overall Risk' , zh_hk: '總體風險'},
    homescreen_overall_risk:       { en_us: 'Overall Risk:', zh_hk: '總體風險'},

    homescreen_basic_risk_title:   { en_us: 'Lifestyle and Physiology' , zh_hk: '生活方式和生理狀況'},
    homescreen_basic_risk:         { en_us: 'Lifestyle and physiology:', zh_hk: '生活方式和生理狀況'},

    homescreen_genetic_risk_title: { en_us: 'Genetics' , zh_hk: '基因檢測'},
    homescreen_genetic_risk:       { en_us: 'Genetics:', zh_hk: '基因檢測'},

    /*summary language*/
    homescreen_summary_risk1:      { en_us: 'Considering your lifestyle, physiology, and genetics, your overall risk is estimated to be ',
                                     zh_hk: '基於您的生活方式、生理指標、基因檢測結果，您的總體風險評級為：'},
    homescreen_summary_risk4:      { en_us: 'Your overall relative risk is around ',
                                     zh_hk: '您的相對總體風險大約是'}, 
    homescreen_gene_risk4:         { en_us: 'Your relative risk is around ',
                                     zh_hk: '您的相對風險大約是'}, 

    /*generic language*/
    homescreen_risk2:                 { en_us: '. You may have a ', 
                                        zh_hk: '。您有'},
    homescreen_risk2_short:           { en_us: ', around ', 
                                        zh_hk: '，大約為'},
    homescreen_risk3:                 { en_us: 'risk of a cardiovascular event over the next 10 years.',
                                        zh_hk: '的風險在未來十年内患心血管疾病。'},

    /*summary language*/
    homescreen_basic_risk1:       { en_us: 'Based just on your lifestyle and physiology, your risk is estimated to be ',
                                    zh_hk: '基於您的生活方式和生理信息，您的風險評級預計為：'}, 
    homescreen_generisk_null:     { en_us: 'We do not know how your genes affect your overall risk. Future research may help to estimate your risk and we will update your results.',
                                    zh_hk: '您的基因與您患病風險的聯繫有待研究。如果將來有新的研究成果，我們會更新您的報告。'},
    homescreen_generisk_lower:    { en_us: 'Your genes may slightly reduce your overall risk. ',
                                    zh_hk: '您的基因會略微降低您的整體患病風險。'},
    homescreen_generisk_same:     { en_us: 'Your genes do not appear to modify your overall risk. ',
                                    zh_hk: '您的基因不會影響您的整體患病風險。'},
    homescreen_generisk_higher:   { en_us: 'Your genes may slightly increase your overall risk. ',
                                    zh_hk: '您的基因會略微提升您的整體患病風險。'},
    homescreen_generisk_sighigher:{ en_us: 'Your genes may significantly increase your overall risk. ',
                                    zh_hk: '您的基因會顯著提升您的整體患病風險。'},
    homescreen_gene_seq_soon:     { en_us: 'Your sample has been genotyped and we are analyzing the results. There will be more information soon.',
                                    zh_hk: '測序已經完成，我們正在分析您的數據，將會很快更新。'},
    homescreen_gene_here:         { en_us: 'Your report is here.',
                                    zh_hk: '我們已為您準備好報告。'},
    homescreen_gene_update:       { en_us: 'Your gene analysis has been updated.',
                                    zh_hk: '我們更新了您的報告。'},
    homescreen_update:            { en_us: "Please tap the 'Calculate Risk' button below to update your basic risk of a cardiovascular event.",
                                    zh_hk: '請點擊"計算風險指數"按鈕來更新您未來10年患心血管疾病的基本風險。'},
    homescreen_share_result:      { en_us: 'Send file to doctor',
                                    zh_hk: '將文件發送給醫生'},
    homescreen_check_status_low:  { en_us: "check status",
                                    zh_hk: '查看狀態'},

    // login screen
    login_Please_fill_in_all_fields:     { en_us: 'Please fill in all fields', 
                                           zh_hk: '請填寫所有字段'},
    login_Password_is_not_correct:       { en_us: 'Password is not correct', 
                                           zh_hk: '密碼錯誤，請重新輸入'},
    login_Passwords_do_not_match:        { en_us: 'Passwords do not match', 
                                           zh_hk: '兩次輸入的密碼不一致，請重新輸入'},
    login_Sign_In:                       { en_us: 'Sign In', 
                                           zh_hk: '登錄'},
    login_Enter_your_password:           { en_us: 'Enter your password', 
                                           zh_hk: '請輸入您的密碼'}, 
    login_Create_Account:                { en_us: 'Create Account', 
                                           zh_hk: '新建賬戶'},
    login_Create_your_password:          { en_us: 'Create your password', 
                                           zh_hk: '請新建您的密碼'}, 
    login_Enter_Password:                { en_us: 'Enter Password', 
                                           zh_hk: '請輸入您的密碼'}, 
    login_Confirm_Password:              { en_us: 'Confirm Password', 
                                           zh_hk: '確認密碼'},
    login_Stay_signed_in:                { en_us: 'Stay signed in', 
                                           zh_hk: '保持登錄'},
    login_Forgot_your_password:          { en_us: 'Forgot your password?', 
                                           zh_hk: '忘記密碼?'},
    login_agree_term_1:                  { en_us: 'By creating an account, you agree to our',
                                           zh_hk: '註冊將代表您已經同意我們的'},
    login_agree_term_2:                  { en_us: 'Terms & Conditions',
                                           zh_hk: '合同與條款'},
    login_sign_in:                       { en_us: 'sign in', 
                                           zh_hk: '登錄'},
    login_no_internet:                   { en_us: 'Please connect to the Internet to create an account',
                                           zh_hk: '請連接網路來創建賬戶'}, 
    
    // account deleted screen
    account_account_deleted: { en_us: 'Account Deleted', 
                               zh_hk: '賬戶已刪除'},
    account_create_notice:   { en_us: 'You can recreate your account with your QR code card. You will need to contact customer support (support@blockdoc.com) \
to be able to redownload your genetics results.', 
                               zh_hk: '您可使用您的私人二維碼再次創建賬戶。您將需要聯繫客戶支持（support@blockdoc.com），以便能夠重新下載您的遺傳學結果。'},
    account_delete_ok:       { en_us: 'OK',
                               zh_hk: '好的'},

    // account delete screen
    account_delete_title:    { en_us: "Are you sure you want to delete your account?",
                               zh_hk: "您確定要刪除您的賬戶嗎？"},
    account_delete_alert:    { en_us: 'All your information will be deleted',
                               zh_hk: '這将刪除您的賬戶和您的所有個人信息。'}, 
    account_delete_password: { en_us: 'Enter your password to delete your account and information.',
                               zh_hk: '請輸入您的密碼以刪除您的賬戶和您的所有個人信息'},
    acccount_password_error: { en_us: 'Password is not correct',
                               zh_hk: '密碼錯誤'},
    account_password_form:   { en_us: 'Please complete form', 
                               zh_hk: '請輸入您的密碼'},
    account_enter_password:  { en_us: 'Enter Password',
                               zh_hk: '輸入密碼'},
    account_password:        { en_us: 'Password',
                               zh_hk: '密碼'},
    account_cancel:          { en_us: 'Cancel',
                               zh_hk: '取消'},
    account_delete:          { en_us: 'Delete Account',
                               zh_hk: '刪除賬戶'},
    account_yes:             { en_us: 'Yes',
                               zh_hk: '是'},
    account_no:              { en_us: 'No',
                               zh_hk: '否'},

    //account screen 
    account_acount_head:     {en_us:  'Account',
                               zh_hk: '賬戶中心'},
    account_user_id:         { en_us: 'User ID',
                               zh_hk: '用戶名'},
    account_version:         { en_us: 'Version',
                               zh_hk: '版'},
    account_sign_out:        { en_us: 'Sign Out',
                               zh_hk: '登出'},
    account_change_password: { en_us: 'Change Password',
                               zh_hk: '修改密碼'},
    account_delete_account:  { en_us: 'Delete Account',
                               zh_hk: '刪除賬戶'},
    account_delete_info:     { en_us: 'All your information will be deleted',
                               zh_hk: '這將刪除您的賬戶和您的所有個人信息'},
    account_support:         { en_us: 'Support Information', 
                               zh_hk: '支持信息'},
    account_chat:            { en_us: 'Chat Support',
                               zh_hk: '聊天支持'},

    //share result
    share_results:           { en_us: 'Share Results',
                               zh_hk: '分享測序結果'}, 
    share_DNA_results:       { en_us: 'Share DNA Results',
                               zh_hk: '分享測序結果'}, 
    share_are_you_sure:      { en_us: 'Are you sure?',
                               zh_hk: '您確定嗎？'}, 
    share_results_detail:    { en_us: 'Click below to share your risk and genotyping results with your doctor.',
                               zh_hk: '请点击下面的按钮与您的医生分享您的结果。'}, 
    share_request1:          { en_us: 'Sharing request:',
                               zh_hk: '分享請求:'}, 
    share_request2:          { en_us: 'You requested us to share your file on ',
                               zh_hk: '您已請求我們在如下時間分享您的文件:'}, 
    share_sharing_status:    { en_us: 'Sharing status:', 
                               zh_hk: '狀態：'},
    share_status_1:          { en_us: 'We have received your sharing request.', 
                               zh_hk: '我們已經收到了您的分享請求。'},
    share_status_2:          { en_us: 'Your result is on the way to the doctor.', 
                               zh_hk: '您的報告在被送向醫生的途中。'},
    share_status_3:          { en_us: 'Your result has been shared with your doctor.', 
                               zh_hk: '我們已經您的與醫生分享您的報告。'},

    // Questionnaire screen basic
    form_basic_title:         { en_us: 'Basics' , 
                                zh_hk: '基本信息'},
    form_basic_continue:      { en_us: 'Continue', 
                                zh_hk: '繼續'},
    form_basic_country_input: { en_us: 'Country or Region', 
                                zh_hk: '請輸入所在國家(地區)'},
    form_basic_country:       { en_us: 'Country or Region' , 
                                zh_hk: '國家(地區)'},
    form_basic_HongKong:      { en_us: 'Hong Kong, China', 
                                zh_hk: '香港,中國'},
    form_basic_China:         { en_us: 'China', 
                                zh_hk: '中國'},
    form_basic_USA:           { en_us: 'USA', 
                                zh_hk: '美國'},
    form_basic_Singapore:     { en_us: 'Singapore', 
                                zh_hk: '新加坡'},
    form_basic_birthday:      { en_us: 'Birth Year', 
                                zh_hk: '出生年份'},
    form_basic_gender:        { en_us: 'Gender', 
                                zh_hk: '性別'},
    form_basic_Male:          { en_us: 'Male', 
                                zh_hk: '男'},
    form_basic_Female:        { en_us: 'Female', 
                                zh_hk: '女'},
    form_basic_height:        { en_us: 'Height (cm)', 
                                zh_hk: '身高(釐米)'},
    form_basic_weight:        { en_us: 'Weight (kg)', 
                                zh_hk: '體重(千克)'},
    form_basic_smoke:         { en_us: 'Smoking' , 
                                zh_hk: '吸煙狀況'},
    form_basic_diabetes:      { en_us: 'Diabetes' , 
                                zh_hk: '糖尿病狀況'},
    form_basic_yes_no:        { en_us: 'Yes/No' , 
                                zh_hk: '是/否'},
    form_basic_please_select: { en_us: 'Please select' , 
                                zh_hk: '請選擇'},

    // Questionnaire screen cardio
    form_cardio_title:        { en_us: 'Lab Values', 
                                zh_hk: '體檢結果'},
    form_lab_result:          { en_us: 'Lab Result',
                                zh_hk: '體檢結果'},
    form_lab_none:            { en_us: 'Not available',
                                zh_hk: '無法使用'},
    form_cardio_calculate:    { en_us: 'Calculate Risk', 
                                zh_hk: '計算風險指數'},
    form_cardio_result:       { en_us: 'See My Risk', 
                                zh_hk: '見我的風險'},
    form_cardio_info:         { en_us: 'Please answer the questions to learn your 10 year ' + 
                                       'risk and recommendations for you. All ' +
                                       'calculations use secure multiparty computation ' + 
                                       'to preserve your privacy.', 
                                zh_hk: '請補全缺失信息以查看十年風險和推薦措施，所有計算過程都使用多方加密算法來保障您的數據安全'}, 
    form_cardio_mpc:          { en_us: 'Calculating your risk' , 
                                zh_hk: '正在計算風險指數'},
    form_cardio_hdl:          { en_us: 'HDL-C (mmol/L)', 
                                zh_hk: '高密度脂蛋白'},
    form_cardio_tc:           { en_us: 'Total Cholesterol (mmol/L)', 
                                zh_hk: '總膽固醇'},
    form_cardio_bp:           { en_us: 'Systolic Blood Pressure (mmHg)', 
                                zh_hk: '血壓(收縮壓)'},
    form_cardio_mmol:         { en_us: '(mmol/L)', 
                                zh_hk: '(mmol/L)'},
    form_cardio_mmHg:         { en_us: '(mmHg)', 
                                zh_hk: '(mmHg)'},
    form_calculate_risk:      { en_us: 'calculate risk',
                                zh_hk: '計算您的風險'},
    form_cardio_optional:     { en_us: 'Optional: Your risk estimate will be more accurate if you also provide recent \
information for your Total Cholesterol, HDL Cholesterol, and blood pressure. If you have this information, please enter \
it below for the most accurate risk estimate.',
                                zh_hk: '可選：如果您還提供有關總膽固醇，HDL膽固醇和血壓的最新信息，則風險估計將更加準確。如果您有此信息，\
請在下面輸入以獲取最準確的風險估算。'},
    // Chat screen
    chat_head:          { en_us: 'Support',
                          zh_hk: '客戶支持'},
    chat_ask_us:        { en_us: 'Ask us...',
                          zh_hk: '請輸入內容'},
    chat_agent_typing:  { en_us: 'Agent is typing...',
                          zh_hk: '客服正在輸入...'},
    chat_send:          { en_us: 'Send',
                          zh_hk: '發送'},
    chat_sendmsg:       { en_us: 'send messages',
                          zh_hk: '發送信息'},
                          

    // Results DNA screen
    result_DNA_title:         { en_us: 'Genetics', 
                                zh_hk: '基因分析'},
    result_status:            { en_us: 'Status:', 
                                zh_hk: '狀態:'},
    result_soon:              { en_us: 'Your result will be available soon', 
                                zh_hk: '您將很快收到分析結果'}, 
    result_download:          { en_us: 'Downloading your genetics result', 
                                zh_hk: '正在下載您的測序結果'}, 
    result_wait_download:     { en_us: 'Please wait while we download your genetics result', 
                                zh_hk: '請稍等, 测序结果下载中'}, 
    result_update:            { en_us: 'We found an updated result', 
                                zh_hk: '分析報告更新中'},
    result_wait_update:       { en_us: 'Please wait while we download your updated genetics result', 
                                zh_hk: '請稍等, 分析報告更新中'},
    result_decrypt:           { en_us: 'Decrypting your result', 
                                zh_hk: '正在解密您的分析报告'},
    result_wait_decrypt:      { en_us: 'Please wait', 
                                zh_hk: '請稍等'}, 
    result_pdf_decrypt:       { en_us: 'Decrypting...', 
                                zh_hk: '正在解密...'},
    result_hacker:            { en_us: 'Download not permitted\n\nSecurity Code 7500\n\nPlease contact customer support at support@blockdoc.com',
                                zh_hk: '不允許下載。\n\n安全代碼7500。\n\n請通過support@blockdoc.com與客戶支持聯繫。.'},
    homescreen_gene_noresultyet:  { en_us: 'No results yet.', zh_hk: '还没有结果。'},

/*
//Status: checking... - this when we are trying to figure out what is going on
{(cryptoState === 'initial') && 
  <View style={styles.row}>
    <Text style={mS.mediumDarkFP}>{i18n.t('result_checking')}</Text>
    <Text style={mS.smallGrayFP}>{i18n.t('result_wait')}</Text>
  </View>
}
*/
    result_checking:  { en_us: 'Status:\nChecking.', zh_hk: '狀態:\n檢查中。'},
    result_wait:      { en_us: 'Please wait', zh_hk: '請稍等'},

/*
//nothing found - this is when the internet is blocked
{(cryptoState === 'nothing') && 
  <View style={styles.row}>
    <Text style={mS.mediumDarkFP}>{i18n.t('result_null')}</Text>
    <Text style={mS.smallGrayFP}>{i18n.t('result_null_exp')}</Text>
  </View>
}
*/

    result_null:     { en_us: 'Status:\nGenetics Report not available.', 
                       zh_hk: '狀態:\n未找到基因檢測報告。'},
    result_null_exp: { en_us: 'Your phone cannot access the Blockdoc servers and there are no results stored on your phone. ' + 
                              'Please connect your phone to the internet to check for genomics results.', 
                       zh_hk: '無法連接到blockdoc服務器，請將手機接入網路來查看結果。'}, 

/*waiting for sample - state 0 right after whitelisting */
    result_userInDB:                  { en_us: 'Status:\nWaiting for your sample.',
                                        zh_hk: '狀態:\n在正等待您的樣本。'},
    homescreen_gene_waitingforblood:  { en_us: 'Waiting for your sample.',
                                        zh_hk: '在正等待您的樣本。'},

/* sample in transit - state 1 */
    result_transit:               { en_us: 'Status:\nYour sample is on the way to the laboratory.', 
                                    zh_hk: '狀態:\n您的本樣正在送往驗室。'}, 
    homescreen_gene_onmyway:      { en_us: 'Your sample is on the way to the laboratory.',
                                    zh_hk: '您的本樣正在送往驗室。'},

/* genotyping in progress - state 2 */
    result_sequencing:            { en_us: 'Status:\nYour sample has arrived at the laboratory and is being genotyped.',
                                    zh_hk: '狀態:\n您的样本已到达实验室，我们正在确定您的基因型。'},
    homescreen_gene_seq_inprog:   { en_us: 'Your sample has arrived at the laboratory and is being genotyped.',
                                    zh_hk: '您的样本已到达实验室，我们正在确定您的基因型。'},

/* genotyping finished - state 3 */
    result_analysis:              { en_us: 'Status:\nGenotyping completed. Computer analysis in progress.', 
                                    zh_hk: '狀態:\n測序結果分析中。正在进行计算机分析。'},
    homescreen_gene_analyzing:    { en_us: 'Genotyping completed. Computer analysis in progress.',
                                    zh_hk: '測序已經完成。正在进行计算机分析。'},

    // Results FRS screen
    result_title :            { en_us: '10 Year Risk', 
                                zh_hk: '十年內患病概率'},
    result_FRS_include :      { en_us: 'This estimate incorporates your genetic risk.', 
                                zh_hk: '基因風險已納入最終評估。' },
    result_FRS_exclude :      { en_us: 'Your risk score will be updated once your genetics report is ready.', 
                                zh_hk: '基因報告準備好後，風險評分將會更新。' },
    result_FRS_you_have :     { en_us: 'You have a ', 
                                zh_hk: '您有 ' },
    result_FRS_10y :          { en_us: ' risk of a cardiovascular event in the next 10 years.', 
                                zh_hk: ' 的風險在未來十年內裡患心血管疾病。' },
    result_FRS_higher1 :      { en_us: ' Your risk is ', 
                                zh_hk: ' 與您的同齡人相比，您的風險是平均風險的 ' },
    result_FRS_higher2 :      { en_us: ' times higher than a typical person of your age. ', 
                                zh_hk: ' 倍。 ' },
    result_FRS_lower1 :       { en_us: ' Your risk is ', 
                                zh_hk: ' 您的風險低於同齡人 ' },
    result_FRS_lower2 :       { en_us: '% lower than a typical person of your age. ', 
                                zh_hk: '%。 ' },
    result_FRS_equal :        { en_us: ' Your risk is similar to that of a typical person of your age. ', 
                                zh_hk: ' 您的風險與您的同齡人相當。' },
    result_FRS_update :       { en_us: 'These numbers may change once your genetics report arrives and we can consider your lifestyle, physiology, and genes.', 
                                zh_hk: '基因報告準備好後，我們將會根據您的生活方式，生理指標和基因信息更新這些數字。' },
    result_FRS_borderline_DNA:{ en_us: '\nSince your risk may be elevated, you should talk to your doctor about steps you can take to reduce your risk.', 
                                zh_hk: '\n您的風險處於臨界值，您應該與您的醫生討論可以採取的降低風險的措施。' },
    result_FRS_borderline:    { en_us: '\nRegardless of the outcome of the genetic testing, the fact that your risk may be elevated suggests that you should talk to your doctor about steps you can take to reduce your risk.', 
                                zh_hk: '\n無論基因檢測的結果如何，您的風險處於臨界值。您應該與您的醫生討論可以採取的降低風險的措施。' },
    result_FRS_elevated_DNA : { en_us: '\nSince your risk may be high, you should talk to your doctor about steps you can take to reduce your risk.', 
                                zh_hk: '\n您的風險較高，您應該盡快與您的醫生討論可以採取的降低風險的措施。' },
    result_FRS_elevated :     { en_us: '\nRegardless of the outcome of the genetic testing, the fact that your risk may be high strongly suggests that you should talk to your doctor about steps you can take to reduce your risk.', 
                                zh_hk: '\n無論基因檢測的結果如何，您的風險較高。您應該盡快與您的醫生討論可以採取的降低風險的措施。' },
    result_FRS_high_DNA :     { en_us: '\nSince your risk may be substantial, you should promptly talk to your doctor about steps you can take to reduce your risk.', 
                                zh_hk: '\n您的風險很高，您應該即刻與您的醫生討論可以採取的降低風險的措施。' },
    result_FRS_high :         { en_us: '\nRegardless of the outcome of the genetic testing, the fact that your risk may be substantial strongly suggests that you should promptly talk to your doctor about steps you can take to reduce your risk.', 
                                zh_hk: '\n無論基因檢測的結果如何，您的風險很高。您應該即刻與您的醫生討論可以採取的降低風險的措施。' },

    result_FRS_risk_is :      { en_us: 'Your risk is', 
                                zh_hk: '您的風險評級是:' },
    result_meaning :          { en_us: 'What does this mean for me?', 
                                zh_hk: '風險詳解' },
    result_advice :           { en_us: 'Things you can do to reduce your risk', 
                                zh_hk: '建議措施' },
    result_blood_pressure :   { en_us: 'Blood pressure:', 
                                zh_hk: '血壓' },
    result_aspirin :          { en_us: 'Aspirin Use:', 
                                zh_hk: '阿司匹林用量' },
    result_statin :           { en_us: 'Statin Use:',
                                zh_hk: '他汀類藥物用量'},
    result_note :             { en_us: 'Note:',
                                zh_hk: '请注意'},
    result_major_r :          { en_us: 'Major risk factors:',
                                zh_hk: '主要風險因素'},
    result_hdl_title :        { en_us: 'HDL Cholesterol:',
                                zh_hk: '高密度脂蛋白'},
    result_tc :               { en_us: 'Total Cholesterol:',
                                zh_hk: '總膽固醇'},
    result_APT:               { en_us: 'Health guidelines',
                                zh_hk: '健康指南'},

    result_smoking :          { en_us: ' Cigarette smoking: please consider quitting smoking',
                                zh_hk: ' 吸煙: 請考慮戒煙'},
    result_hypertension :     { en_us: ' Hypertension: your blood pressure is above 140/90 mmHg',
                                zh_hk: ' 血壓: 您的血壓過高 (血壓 \u2265 140/90 mmHg)'},
    result_diabetes :         { en_us: ' Diabetes: please work with your doctor to manage your diabetes',
                                zh_hk: ' 糖尿病: 請定期進行檢查'},
    result_hdl :              { en_us: ' Low HDL cholesterol: your HDL is below 1.1 mmol/L',
                                zh_hk: ' 高密度脂蛋白: 您的高密度脂蛋白過低 (高密度脂蛋白 < 1.1 mmol/L)'},
    result_age_male :         { en_us: ' Age: (Age \u2265 45 years)',
                                zh_hk: ' 年齡因素 (年齡 \u2265 45周歲) '},
    result_age_female :       { en_us: ' Age: (Age \u2265 55 years)',
                                zh_hk: ' 年齡因素 (年齡 \u2265 55周歲)'},

    // Code scanner screen
    code_detect_fail:    { en_us: 'Did not detect Blockdoc QR code - make sure QR code is in focus and that you are scanning your Blockdoc QR card.',
                           zh_hk: '未檢測到Blockdoc二維碼，請確保二維碼始終處於鏡頭內并且您正在掃描您卡上的二維碼'},
    code_please_scan:    { en_us: 'Please scan your QR code',
                           zh_hk: '請掃描您的二維碼'},
    code_tap_to_scan:    { en_us: 'Scan again',
                           zh_hk: '再次掃描'},
    code_request_camera: { en_us: 'Requesting camera permission',
                           zh_hk: '請求相機許可權'},
    code_no_access:      { en_us: 'No access to camera',
                           zh_hk: '無法訪問相機'},

    // password change screen
    password_change_header:      { en_us: 'Change Password',
                                   zh_hk: '修改密碼'},
    password_current_password:   { en_us: 'Current Password',
                                   zh_hk: '舊密碼'},
    password_new_password:       { en_us: 'New Password',
                                   zh_hk: '新密碼'},
    password_confirm_password:   { en_us: 'Confirm Password',
                                   zh_hk: '確認新密碼'},
    password_change_password:    { en_us: 'Change Password',
                                   zh_hk: '重置密碼'}, 
    password_cancel:             { en_us: 'Cancel',
                                   zh_hk: '取消'},
    password_incorrect_password: { en_us: 'Old password is not correct',
                                   zh_hk: '舊密碼錯誤'},
    password_missing_parameter:  { en_us: 'Please provide the previous password and the new password',
                                   zh_hk: '請填寫舊密碼和新密碼'},
    password_password_mismatch:  { en_us: 'New passwords do not match',
                                   zh_hk: '兩次輸入的密碼不一致，請重新輸入'}, 
    password_password_same:      { en_us: 'New password is the same as the old one',
                                   zh_hk: '新密碼與舊密碼相同，請換一個密碼'}, 
    password_Password_Changed:   { en_us: 'Password Changed',
                                   zh_hk: '密碼已修改'}, 
    password_Password_Forgot:    { en_us: 'Forgot Password',
                                   zh_hk: '密碼中心'}, 

    // forgot password
    forget_password_header:   { en_us: 'Forgot Password',
                                zh_hk: '密碼中心'},
    forget_password_security: { en_us: 'To ensure your privacy, your data are only stored on your phone. ' +
                                        'We do not have access to your information.',
                                zh_hk: '為確保您的隱私安全，您的數據將僅存儲于您的手機上，我們無法訪問您的數據。'},
    forget_password_info:     { en_us: "\nIf you've forgotten your password and you have the QR code you used to create your account, you can:",
                                zh_hk: '\n如果您已經忘記密碼，但是擁有用於創建賬戶的二維碼，那麼您可以:'},
    forget_password_step1:    { en_us: 'Tap the Delete Account button below to delete your account and information.',
                                zh_hk: '點擊刪除賬戶的按鈕來刪除您的賬戶和您的所有信息。'},
    forget_password_step2:    { en_us: 'Use your QR code to create a new account.',
                                zh_hk: '再次掃描您的二維碼來新建的賬戶。'},
    forget_password_step3:    { en_us: 'Re-enter your information.',
                                zh_hk: '重新輸入您的信息。'},
    forget_password_step4:    { en_us: 'Your test results will then reappear in the app.',
                                zh_hk: '完成信息輸入后，您的測試結果將再次出現在APP中。'}, 
    forget_password_try:      { en_us: "If you'd like to try to enter your password again, tap ",
                                zh_hk: '如果您想再次嘗試輸入密碼，請點擊'},
    forget_password_go_back:  { en_us: 'Go Back to Sign In',
                                zh_hk: '返回'},
    forget_password_below:    { en_us: ' below.',
                                zh_hk: '。'},
    forget_password_delete:   { en_us: 'Delete Account',
                                zh_hk: '刪除賬戶'},
    
    // App screen
    app_blockdoc_precision_health: { en_us: 'Blockdoc',
                          zh_hk: 'Blockdoc'}, 
    app_blockdoc:       { en_us: 'Learn about your health risks based on your physiology, lifestyle, and genes.',
                          zh_hk: '根據您的生理狀況，生活方式和遺傳信息了解您的健康風險'},
    app_MPC_title:      { en_us: 'Private Computation',
                          zh_hk: '加密計算'},
    app_MPC_content:    { en_us: 'Data we exchange with you are cryptographically split, processed, and recombined so your medical information stays private.',
                          zh_hk: '我们与您交换的数据以加密方式进行分割，处理和重新组合，以便您的醫療信息保持私密狀態。'},
    app_create_account: { en_us: 'Create an Account',
                          zh_hk: '創建賬戶'},
    app_scan_card:      { en_us: 'by scanning your QR key card and setting your password.',
                          zh_hk: '通過掃描您的秘鑰卡來設置登錄密碼'}, 
    app_key_card:       { en_us: 'Your QR key card',
                          zh_hk: '私人秘鑰卡'},
    app_key_access:     { en_us: 'allows only you to access your results. Please keep the QR card safe.',
                          zh_hk: '秘鑰卡是您能訪問結果的唯一憑證，請妥善保管'}, 
    app_next:           { en_us: 'Next',
                          zh_hk: '繼續'},
    app_sign_up:        { en_us: 'Sign Up',
                          zh_hk: '登錄'},
    
    // Results FRS screen - long report
    result_frs_low:        { en_us: 'You have a low risk of cardiovascular disease and stroke.',
                             zh_hk: '您患心血管疾病和中風的風險較低。'},
    result_frs_elv:        { en_us: 'You may be at slightly elevated risk for cardiovascular disease or stroke. \
You should consider improving your lifestyle - please ask your doctor for advice.',
                             zh_hk: '您患心血管疾病和中風的風險有上升的趨勢，您應該考慮改善您的生活方式，建議如下。'}, 
    result_frs_high:       { en_us: 'You may have a higher than average risk for cardiovascular disease or stroke. \
You should definitely talk to your doctor and improve your lifestyle.',
                             zh_hk: '您患心血管疾病和中風的風險高於平均水平，請一定聽從醫生建議改善生活方式，建議如下。'},
    result_frs_severe:     { en_us: 'You may be at significant risk for cardiovascular disease or stroke. You should \
promptly talk to your doctor and improve your lifestyle. Statin use will almost certainly be warranted.',
                             zh_hk: '您患心血管疾病和中風的風險非常高，請盡快聽從醫生建議改善生活方式以及在必要時服用他汀類藥物。'}, 
    result_frs_null:       { en_us: 'Not enough data. Please complete the questionnaire.',
                             zh_hk: '請補全缺失信息。'},
    result_bp_low:         { en_us: 'Your blood pressure appears to be well-controlled. Keep up the good work!',
                             zh_hk: '您的血壓控制良好，請繼續保持！'},
    result_bp_elv:         { en_us: 'Your blood pressure may be elevated. You should take steps to reduce your blood pressure. \
Those steps might include exercising regularly, eating a healthy diet, reducing sodium in your diet, and limiting the amount of alcohol you drink.',
                             zh_hk: '您的血壓有上升的趨勢。您應該採取措施降低血壓。這些措施可能包括定期鍛煉，健康飲食，減少食鹽攝入，以及限制飲酒。'},
    result_bp_hig:        { en_us: 'Your blood pressure appears to be poorly controlled. \
You should talk to your doctor about thiazide diuretics, ACEI/ARB, or calcium channel blockers.',
                             zh_hk: '您的血壓過高。您應該和醫生討論使用噻嗪類利尿劑，ACEI/ARB或鈣通道阻滯劑的可能性。'}, 
    result_statin_low:     { en_us: 'There is no indication to be on a statin.',
                             zh_hk: '您無需服用他汀類藥物。'},
    result_statin_mod:     { en_us: 'There is no indication to be on a statin.',
                             zh_hk: '您無需服用他汀類藥物。'},
    result_statin_bor:     { en_us: 'You should talk to your doctor about a moderate intensity statin and lifestyle interventions. \
Moderate intensity statins include atorvastatin 10 mg, pravastatin 40 mg, and simvastatin 20 - 40 mg. Your doctor will advise.',
                             zh_hk: '您應該和醫生談談服用適量的他汀類藥物(例如阿托伐他汀10 mg，普伐他汀40 mg，辛伐他汀20 - 40 mg)并調整生活方式，請遵醫囑。'},
    result_statin_ele:     { en_us: 'You should talk to your doctor about a moderate intensity statin and lifestyle interventions. \
Moderate intensity statins include atorvastatin 10 mg, pravastatin 40 mg, and simvastatin 20 - 40 mg. Your doctor will advise.',
                             zh_hk: '您應該和醫生談談服用適量的他汀類藥物(例如阿托伐他汀10 mg，普伐他汀40 mg，辛伐他汀20 - 40 mg)并調整生活方式，請遵醫囑。'},
    result_statin_hig:     { en_us: 'You should talk to your doctor about a high intensity statin and lifestyle interventions. \
A high intensity statin may be, for example, atorvastatin 40 to 80 mg. Your doctor will advise.',
                             zh_hk: '您應該和醫生談談服用高劑量的他汀類藥物(例如阿托伐他汀40mg至80mg)并調整生活方式，請遵醫囑。'},
    result_aspirin_yes:    { en_us: 'On the basis of your age and risk for heart disease or stroke, which is over 10%, \
please talk to your doctor about low-dose aspirin for the primary prevention of cardiovascular disease. Your doctor will \
consider additional factors such as your bleeding risk and willingness to take aspirin for at least 10 years.',
                             zh_hk: '基於您的年齡信息以及風險指數(超過10%)，請和醫生討論使用低劑量阿司匹林來進行心血管疾病預防的可能性。您的醫生將會考慮其他因素，例如您長期服用阿司匹林(至少10年)的意願，以及可能導致的凝血障礙。'},
    result_aspirin_no:     { en_us: 'On the basis of your age and risk for heart disease or stroke, which is lower than 10%, \
you are not likely to benefit from low-dose aspirin.',
                             zh_hk: '基於您的年齡信息以及風險指數(低於10%)，您不太可能從阿司匹林中獲益。'},
    result_aspirin_null:   { en_us: 'On the basis of your age, there is insufficient \
evidence you will benefit from aspirin as a way of reducing your risk of heart disease and stroke.',
                             zh_hk: '基於您的年齡信息，沒有充分證據表明阿司匹林能助您降低患心血管疾病和中風的風險。'},
    result_general_note:   { en_us: 'Guidelines stress the importance of lifestyle modifications to lower \
cardiovascular disease risk in all patients. This includes eating a heart-healthy diet, regular \
aerobic exercise, maintenance of desirable body weight and avoidance of tobacco products.',
                             zh_hk: '建議強調了改變生活方式對降低患心血管疾病風險的重要性。這其中包括了改善飲食，加強週期性有氧鍛煉，保持體重以及避免煙草製品等。'},
    /*Please check English below*/
    result_cholesterol_low:{ en_us: 'Your total cholesterol is well controlled. Keep up the good work!',
                             zh_hk: '您的總膽固醇控制良好，請繼續保持！'},
    result_cholesterol_bor:{ en_us: 'Your total cholesterol may be close to borderline. Please consider improving your lifestyle. Ideally, your total cholesterol should be below 5.2 mmol/L.',
                             zh_hk: '您的總膽固醇可能接近臨界值，請考慮改善您的生活方式。理想情況下，您的總膽固醇應保持在 5.2 mmol/L 之下。'},
    result_cholesterol_hig:{ en_us: 'Your total cholesterol may be high. Please talk to your doctor. Ideally, your total cholesterol should be below 5.2 mmol/L.',
                             zh_hk: '您的總膽固醇可能很高，請諮詢您的醫生。理想情況下，您的總膽固醇應保持在 5.2 mmol/L 之下。'},
    result_hdl_low:        { en_us: 'Your HDL-C may be low. Please talk to your doctor. Ideally, your HDL-C would be above 1.1 mmol/L. To increase your HDL-C, \
you should consider quitting smoking (if you are a smoker) and exercising more.',
                             zh_hk: '您的高密度脂蛋白可能较低。請諮詢您的醫生。理想情況下，您的高密度脂蛋白應介於1.1-1.6 mmol/L之間。'},
    result_hdl_norm:       { en_us: 'Your HDL-C level is average. You can further reduce your cardiovascular risk by increasing your HDL-C levels, such as by \
quitting smoking (if you are a smoker) and exercising more.',
                             zh_hk: '您的高密度脂蛋白控制良好。請繼續保持！'},
    result_hdl_hig:        { en_us: 'Your HDL-C is higher than average, which may reduce your cardiovascular risk. Keep up the good work.',
                             zh_hk: '您的高密度脂蛋白可能较高。請諮詢您的醫生。理想情況下，您的高密度脂蛋白應介於1.1-1.6 mmol/L之間。'},
    /*Please check English above - removed the word 'too'*/
    }

en_us = SelectObject(Strings_Dict, 'en_us');
zh_hk = SelectObject(Strings_Dict, 'zh_hk');

i18n.defaultLocale = 'en_us';
i18n.locale = Localization.locale.includes('zh') ? 'zh_hk' : 'en_us';
//i18n.locale = 'zh_hk';
i18n.fallbacks = true;
i18n.translations = {en_us, zh_hk};

export default i18n;
