
// USER
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const USER_SIGNIN_TOKEN_GEN = 'USER_SIGNIN_TOKEN_GEN';
export const USER_RESET_ERROR = 'USER_RESET_ERROR';
export const SET_UNREAD_COUNT = 'SET_UNREAD_COUNT';
export const RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION';
export const RESET_APP = 'RESET_APP';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const SHARE_DNA = 'SHARE_DNA';
export const SHARE_DNA_SUCCESS = 'SHARE_DNA_SUCCESS';
export const SHARE_DNA_FAILURE = 'SHARE_DNA_FAILURE';
export const PREPORT = 'PREPORT';
export const PREPORT_SUCCESS = 'PREPORT_SUCCESS';
export const PREPORT_FAILURE = 'PREPORT_FAILURE';
export const INTERNET_STATUS = 'INTERNET_STATUS';
export const GET_SHARING_STATE_SUCCESS = 'GET_SHARING_STATE_SUCCESS';
export const GET_SHARING_STATE_FAILURE = 'GET_SHARING_STATE_FAILURE';
export const GET_SHARING_STATE = 'GET_SHARING_STATE';
export const GET_PREPORT_STATE_SUCCESS = 'GET_PREPORT_STATE_SUCCESS';
export const GET_PREPORT_STATE_FAILURE = 'GET_PREPORT_STATE_FAILURE';
export const GET_PREPORT_STATE = 'GET_PREPORT_STATE';
export const SB_CONNECTED = 'SB_CONNECTED';

// WHITELIST
export const GET_STATUS = 'GET_STATUS';
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAILURE = 'GET_STATUS_FAILURE';
export const CIRCULATE_STATUS = 'CIRCULATE_STATUS';

// ANSWER
export const GIVE_ANSWER = 'GIVE_ANSWER';
export const GIVE_ANSWER_SUCCESS = 'GIVE_ANSWER_SUCCESS';
export const GIVE_ANSWER_FAILURE = 'GIVE_ANSWER_FAILURE';
export const GET_ANSWERS = 'GET_ANSWERS';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const GET_FRS_SUCCESS = 'GET_FRS_SUCCESS';
export const GET_ANSWERS_FAILURE = 'GET_ANSWERS_FAILURE';

// RESULT
export const UPDATE_RESULT_FLAG = 'UPDATE_RESULT_FLAG';
export const UPDATE_RESULT_FLAG_SUCCESS = 'UPDATE_RESULT_FLAG_SUCCESS';
export const UPDATE_RESULT_FLAG_FAILURE = 'UPDATE_RESULT_FLAG_FAILURE';
export const GET_RESULTS = 'GET_RESULTS';
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
export const GET_RESULTS_FAILURE = 'GET_RESULTS_FAILURE';
export const CIRCULATE_LOCAL_RESULTS = 'CIRCULATE_LOCAL_RESULTS';

// SCORES
export const CALCULATE_RISK_SCORE = 'CALCULATE_RISK_SCORE';
export const CALCULATE_RISK_SCORE_SUCCESS = 'CALCULATE_RISK_SCORE_SUCCESS';
export const CALCULATE_RISK_SCORE_FAILURE = 'CALCULATE_RISK_SCORE_FAILURE';
export const CALCULATE_RISK_SCORE_PROGRESS = 'CALCULATE_RISK_SCORE_PROGRESS';

//Secure storage locations
export const SECURE_STORAGE_USER_ACCOUNT = 'UserAccount';
export const SECURE_STORAGE_ANSWERS = 'Answers'; //used to store the user's answers to the questionaire
export const SECURE_STORAGE_FRS = 'FRS';
export const SECURE_STORAGE_USER_FLOW = 'UserFlow';
export const SECURE_STORAGE_USER_RESULT = 'UserResult';
export const SECURE_STORAGE_USER_STATUS = 'UserStatus';
