
// USER
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const USER_RESET_ERROR = 'USER_RESET_ERROR';
export const RESET_APP = 'RESET_APP';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// ANSWER
export const GIVE_ANSWER = 'GIVE_ANSWER';
export const GIVE_ANSWER_SUCCESS = 'GIVE_ANSWER_SUCCESS';
export const GIVE_ANSWER_FAILURE = 'GIVE_ANSWER_FAILURE';
export const GET_ANSWERS = 'GET_ANSWERS';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const GET_ANSWERS_FAILURE = 'GET_ANSWERS_FAILURE';
export const GET_SMC_SUCCESS = 'GET_SMC_SUCCESS';

// RESULT
export const GET_RESULTS = 'GET_RESULTS';
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
export const GET_RESULTS_FAILURE = 'GET_RESULTS_FAILURE';
export const CIRCULATE_LOCAL_RESULTS = 'CIRCULATE_LOCAL_RESULTS';

// SCORES
export const SECURE_COMPUTE = 'SECURE_COMPUTE';
export const SECURE_COMPUTE_SUCCESS = 'SECURE_COMPUTE_SUCCESS';
export const SECURE_COMPUTE_FAILURE = 'SECURE_COMPUTE_FAILURE';
export const SECURE_COMPUTE_PROGRESS = 'SECURE_COMPUTE_PROGRESS';

// Secure storage locations
export const SECURE_STORAGE_ACCOUNT = 'Account';
export const SECURE_STORAGE_ANSWERS = 'Answers';
export const SECURE_STORAGE_SMC = 'SMC';